ShieldBattery/ShieldBattery

docs/GETTING_STARTED.md

- removes `SHIELDBATTERY_PATH` mention
- edits redis' description a bit
- removes setting up the initial user part
- adds the instructions to set up map system

Update getting started guide to reflect current state of the project.

---

client/lobbies/join-lobby.css
client/lobbies/join-lobby.jsx
client/lobbies/loading.jsx
client/lobbies/lobby.jsx
client/maps/map-list.jsx
client/maps/map-thumbnail.jsx
client/maps/maps.css

This commit also refactors the MapThumbnail component, so it can be used
in more advanced ways.

Implement a MapList component, used to display a list of maps.

---

game/node-bw/brood_war.cpp
game/node-bw/brood_war.h
game/node-bw/observing_patches.cpp
game/node-bw/observing_patches.h

- Center screen on one of players at start for observers
- Observers are shown in net timeout dialog
- Vision dialog says "Players" instead of "Replay players"

Additional ingame observing patches

---

client/dialogs/connected-dialog-overlay.jsx
client/download/update-dialog.jsx
client/main-layout.css
client/main-layout.jsx
client/matchmaking/accept-match.jsx
client/material/dialog.css
client/material/dialog.jsx
client/material/portal.css
client/material/portal.jsx
client/styles/global.css

Note: Modal dialogs are not working in this commit. Need to rethink how
the modal dialogs/portals should work and fix it.
Fixes #299

Move the Dialog component to Portals.

---

server/app.js
server/lib/api/bans.js
server/lib/api/users.js
server/lib/mail/templates/email-verification.html
server/lib/mail/templates/email-verification.txt
server/lib/models/email-verifications.js
server/lib/models/users.js
server/lib/session/email-session-middleware.js
server/lib/session/init.js
server/lib/session/middleware.js
server/lib/session/session-store.js
server/lib/session/update-all-sessions.js
server/lib/verifications/send-account-verification-email.js
server/lib/websockets/socket-groups.js
server/mail-templates/README.md
server/mail-templates/email-verification.html
server/migrations/20170731105206-add-email-verifications.js
server/routes.js

Everytime a new account is created, we send an account verification
email to the user. There are two new routes added in this commit; one to
actually verify an user's email, and one to resend the verification
email.

Implement the server side necessary for email verification.

---

server/lib/api/maps.js
server/lib/api/patches.js
server/lib/file-upload/handle-multipart-files.js

koa-body had breaking changes which weren't noticed when it was updated ( https://github.com/dlau/koa-body/blob/master/CHANGELOG.md#breaking-changes-in-v34 )

Fix map uploading

---

app/build-native-modules.js
app/native/process/module.cpp
app/native/process/v8_string.cpp
app/native/process/wrapped_process.cpp

(Also make the script for building app's native module display msbuild output)

Build on node 12

---

client/active-game/active-game-manager.js
client/lobbies/create-lobby.jsx
client/lobbies/lobby-preferences-reducer.js
client/lobbies/socket-handlers.js
client/maps/browse-server-maps.jsx
client/maps/map-select.jsx
client/maps/map-thumbnail.jsx
client/maps/maps-reducer.js
server/lib/api/lobbyPreferences.js
server/lib/api/maps.js
server/lib/lobbies/lobby.js
server/lib/models/lobby-preferences.js
server/lib/models/maps.js
server/lib/models/matchmaking-map-pools.js
server/lib/models/matchmaking-preferences.js
server/lib/wsapi/lobbies.js
server/migrations/20191128135335-refactor-uploaded-maps-model.js
server/test/lobbies/lobby.js

Read the migration file added in this commit to see how the database
schema changed.

Refactor the map model in preparation for upcoming features.

---

server/lib/api/maps.js
server/lib/models/maps.js

For now, only `name`, `description` and `visibility` can be updated.
In future, users will also be able to update the map file itself.

Add server-side support for updating maps.

---

app/common/maps.js
client/maps/action-creators.js
client/maps/browse-server-maps.jsx
client/maps/browser-footer.jsx
server/lib/api/maps.js
server/lib/models/maps.js

Also an option to control the thumbnail size.

Implement the ability to filter and sort maps.

---

README.md

Replace the now deprecated IRC link with the little less deprecated

---

game/src/bw.rs
game/src/bw_1161.rs
game/src/bw_scr.rs

Had to update MapDirEntry struct and LobbyDialogVtable.
That vtable has changed twice recently, the relevant offset should probably
be determined dynamically.

Compatibility with SCR 8310

---

game/src/forge/mod.rs

Makes SCR's fullscreen modes create window without long black screens
+ the game won't move the mouse cursor around during loading

Scr fullscreen

---

client/active-game/active-game-manager.js
client/matchmaking/socket-handlers.js
server/lib/games/game-loader.js
server/lib/matchmaking/match-acceptor.js
server/lib/models/maps.js
server/lib/wsapi/lobbies.js
server/lib/wsapi/matchmaking.js

Make the matchmaking actually launch the game when all players accept

---

game/Cargo.lock
game/Cargo.toml
game/src/bw_scr.rs
game/src/bw_scr/commands.rs

Detects when a player seeks backwards, and in that case re-runs game loop
after it exits.

Fix scr replay seeking

---

game/Cargo.lock
game/Cargo.toml
game/src/bw.rs
game/src/bw_1161.rs
game/src/bw_scr.rs
game/src/bw_scr/bw_hash_table.rs
game/src/crash_dump.rs
game/src/game_state.rs
game/src/lib.rs
game/src/snp.rs

Team melee does not work yet. Should be relatively simple to do though.

Add SCR multiplayer

---

client/activities/activity-button.jsx
client/avatars/avatar-button.jsx
client/main-layout.jsx
client/matchmaking/searching-match-nav-entry.jsx
client/profile/nav-entry.jsx
client/profile/self-profile-overlay.jsx

Currently, the popover that is shown when clicking on a "Searching..."
icon is a temporary one that only allows for canceling the search. In
future, this popover should display a bit more info about what you
queued for and with what settings, but that needs to be designed first.

Implement a UI when searching for a match.

---

client/admin/map-manager.jsx
client/admin/panel.jsx
client/admin/permissions-reducer.js
client/admin/permissions.jsx
client/auth/auth-records.js
server/lib/api/maps.js
server/lib/file-upload/aws.js
server/lib/file-upload/index.js
server/lib/file-upload/local-filesystem.js
server/lib/models/maps.js
server/lib/models/permissions.js
server/migrations/20200825152459-add-delete-maps-permission.js
server/migrations/20200825152459-add-mass-delete-maps-permission.js

This feature enables users with a special permission to delete all maps
from the database, and their associated files. Use with care.

Implement ability to delete all maps.

---

common/async/deferred.js
common/async/swallow-non-builtins.js
server/lib/games/game-loader.js
server/lib/games/gen-result-code.js
server/lib/games/registration.js
server/lib/models/games-users.js
server/lib/models/games.js
server/lib/models/users.js
server/lib/wsapi/lobbies.js
server/lib/wsapi/matchmaking.js
server/migrations/20200822075547-add-game-results.js
server/migrations/20200825155547-add-game-results.js

This does not deal with game results at all yet, and result codes are not yet distributed to clients.

Register games in the DB

---

client/actions.js
client/auth/auth-reducer.js
client/auth/auther.js
client/auth/edit-account.jsx
client/dialogs/connected-dialog-overlay.jsx
client/navigation/connected-left-nav.jsx
server/lib/api/users.js
server/lib/mail/templates/password-change.html
server/lib/mail/templates/password-change.txt
server/mail-templates/password-change.html

Allow user to change their password while logged in.

---

client/auth/auth-records.js
client/auth/auth-reducer.js
client/auth/edit-account.jsx
client/forms/form.jsx
client/forms/validators.js
client/index.jsx
client/material/text-field.jsx
server/lib/api/users.js
server/lib/mail/templates/email-change.html
server/lib/mail/templates/email-change.txt
server/lib/models/users.js
server/mail-templates/email-change.html

Allow users to change their email while logged in.

---

app/local-settings.js
client/audio/audio-manager.js
client/icons/material/play_arrow-24px.svg
client/icons/material/stop-24px.svg
client/material/dialog.jsx
client/settings/app-settings.jsx
client/settings/game-settings.jsx
client/settings/ipc-handlers.js
client/settings/reducer.js
client/settings/settings.jsx

Add a way to control the audio's master volume setting.

---

game/Cargo.lock
game/Cargo.toml
game/src/bw.rs
game/src/bw_scr.rs
game/src/game_state.rs
server/lib/lobbies/lobby.js
test/server/lib/lobbies/lobby.js

Would be nice if someone verified that it works fine for them as well, as there already were more issues than the single one I expected there to be.

SCR team game support

---

client/app-bar/lockup.jsx
client/main-layout.jsx

Add version number to app bar

---

client/beta/splash.jsx
client/beta/top-links.jsx
server/views/layout.jade

mobile resolutions.
Fixes #402

Update the splash page to be more responsive so it's actually usable on

---

client/lobbies/socket-handlers.js
client/matchmaking/find-match.jsx
client/matchmaking/socket-handlers.js

Now the the whole map pool is downloaded as soon as the player enters
the queue.
Fixes #483

Optimize map downloads in the matchmaking.

---

client/chat/channel.jsx

No idea if this is actually desired, no biggie if not.

Add user highlight when overlay is open

---

client/actions.ts
client/main-layout.jsx
client/matchmaking/elapsed-time.tsx
client/matchmaking/find-match.jsx
client/matchmaking/matchmaking-reducer.js
client/matchmaking/matchmaking-searching-overlay.jsx
client/matchmaking/searching-match-nav-entry.jsx
client/matchmaking/socket-handlers.js
client/navigation/connected-left-nav.jsx
package.json
server/webpack.config.js
webpack.config.js

Update the design of the searching match overlay to match the latest

---

client/lobbies/active-lobby.jsx
client/lobbies/devonly/active-test.jsx
client/lobbies/devonly/routes.jsx
client/lobbies/view.jsx

For now we're not reusing code from the matchmaking screen, as it's not
clear yet if those two designs will diverge significantly or not.

Add an active lobby screen similar to the one we're using in matchmaking.

---

docs/GETTING_STARTED.md

Add documentation on how to obtain `stardat.mpq` and `broodat.mpq` now that they are no longer included with SCRM.

Add documentation on how to obtain stardat.mpq and broodat.mpq

---

app/system-tray.js

Add a system tray menu option for opening the logs directory

---

client/activities/activity-overlay.jsx

Move activities overlay to render underneath the appbar

---

game/Cargo.lock
game/Cargo.toml
game/scr-analysis/src/lib.rs
game/src/bw.rs
game/src/bw/unit.rs
game/src/bw_1161.rs
game/src/bw_1161/observing.rs
game/src/bw_scr.rs
game/src/game_state.rs
game/src/game_thread.rs

IMO this is all we need to improve with stacked buildings.
Obviously doesn't clutter the status screen when the building isn't stacked

Show building stack count in status screen if they're stacked

---

client/material/popover.jsx

Fixes #641 
Popovers should now be forced to stay in the window if the prop is set.

Keep popover in window

---

client/chat/chat-message-layout.tsx
client/chat/chat-reducer.js
client/lobbies/lobby-message-layout.tsx
client/messaging/common-message-layout.tsx
client/messaging/message-layout.tsx
client/messaging/message-list.tsx
client/messaging/message-records.ts

Also reorganizes the message layout stuff a bit. Now a
common-message-layout file contains the implementation of the messages
that are common to all chat services, and message-layout file is a mixed
bag of primitives which can be used to style different kinds of
messages. The organization of this file might need some further
organization at some point, but should be fine for now.

Add a message to the chat when a day changes between any two messages.

---

server/http-apis.ts
server/lib/chat/chat-api.ts

moved to HTTP in the next PR).

Add a HTTP-based chat API (client is still using the WS API; will be

---

server/lib/parties/party-api.ts
server/lib/parties/party-service.test.ts
server/lib/parties/party-service.ts

Inviting multiple users at once is more headache than it's worth.

Make the parties `invite` API only accept a single user.

---

game/Cargo.lock
game/scr-analysis/Cargo.toml
game/scr-analysis/src/lib.rs
game/src/bw.rs
game/src/bw_1161.rs
game/src/bw_1161/storm.rs
game/src/bw_scr.rs

Tested that this worked whenplaying alone with the patch from yesterday that got rolled back, but probably would be good to test with the this "good patch" that the game was reverted to before merging this PR. (It is supposed to work with both patches)

Update scr-analysis to support newer versions

---

client/chat/channel.tsx

Changed:
* Changed Userlist from being a class component to using hooks
* Refactored the logic to render the rows and get height
* Removed padding from being a row that's rendered to padding on the container

Change Userlist to use react-window - Partially fixes #690

---

app/app.ts
app/settings.ts
client/settings/app-settings.jsx
client/settings/settings-records.ts
common/local-settings.ts

This closes https://github.com/ShieldBattery/ShieldBattery/issues/276
I was also thinking about the more verbose `Run Shield Battery when my computer starts.` which is effectively what steam's equivalent setting is. Also this defaults to not opening on start, i'm not sure what your preference is.

Add setting to open on boot

---

game/Cargo.lock
game/Cargo.toml
game/scr-analysis/Cargo.toml
game/scr-analysis/src/lib.rs
game/src/bw/list.rs
game/src/bw_scr.rs
game/src/bw_scr/game.rs
game/src/game_thread.rs
game/src/replay.rs

Fixes flying SCVs and a mineral hack

Implement better rules to limit order queues

---

client/chat/channel.tsx
client/chat/chat-message-layout.tsx
client/chat/chat-message-records.ts
client/chat/chat-reducer.ts
client/lobbies/lobby-message-layout.tsx
client/lobbies/lobby-message-records.ts
client/lobbies/lobby-reducer.js
client/lobbies/lobby.tsx
client/material/popover.tsx
client/messaging/common-message-layout.tsx
client/messaging/connected-username.tsx
client/messaging/message-layout.tsx
client/messaging/message-list.tsx
client/messaging/message-records.ts
client/profile/user-profile-overlay.tsx
client/whispers/whisper-reducer.ts
server/lib/wsapi/lobbies.js

Clicking the username will open the profile overlay for the clicked
user.
NOTE 1: There's no hover effect atm besides changing the cursor to
pointer. Might be worth it to add some color change as well.
NOTE 2: There's some weird ass bug atm where hovering on some names
doesn't make the whole name clickable, only parts of it.

Make the username in messaging-related components clickable.

---

game/scr-analysis/src/lib.rs
game/src/bw_scr.rs

Fix a desync issue with obs ui

---

client/activities/activity-button.tsx
client/main-layout.tsx
client/material/button.tsx
client/notifications/activity-bar-entry.tsx

Well, except the IconButton. IconButtons should probably display their
hotkeys in a tooltip or something.

Generalize the hotkey label to all buttons as well.

---

client/navigation/connected-left-nav.tsx

Also adds a nicer tooltip (with hotkey noted) for those buttons.

Add a hotkey to join a channel and start a whisper session.

---

client/auth/auth-records.ts
client/profile/user-profile-admin.tsx
common/users/permissions.ts
server/lib/models/permissions.ts
server/lib/users/user-api.ts
server/migrations/20220219113616-remove-edit-all-channels-permission.js

I have no idea what was the idea behind this permission when I first
added it, but I'm fairly certain that it's way too general and ambiguous
for it to make sense to keep.

Remove `editAllChannels` permission.

---

docs/GETTING_STARTED.md
sample.env

getting started guide to the sample env file.
Also fix some outdated information in the getting started guide.

Add a couple of environment variables that were mentioned in the

---

server/lib/ladder/ladder-api.ts

This PR only updates the server code to allow logged out users to
request ladder rankings. The frontend changes that allows logged out
users to actually see the ladder page will need to be done separately.
Additionally, this PR adds a throttle to the get rankings route.

Make the route to get ladder rankings available to logged out users.

---

client/dialogs/action-creators.ts
client/dialogs/connected-dialog-overlay.tsx
client/main-layout.tsx
client/material/zindex.js
client/settings/action-creators.ts
client/settings/starcraft-path-dialog.jsx
client/starcraft/starcraft-health.jsx

For some reason it didn't cross my mind to use the only place where we
actually have dialog stacking to test it when I added dialog history,
and instead I tested it by creating a dummy dialog stacking in Join
Channel dialog just for testing purposes. Oops.

Fix the Starcraft Path dialog closing issues now that the dialogs stack.

---

client/replays/browse-local-replays.tsx
common/maps.ts
server/lib/maps/map-parse-worker.js

Sanitize map name in the replay browser.

---

deployment/appserver/db/postgresql.conf
deployment/appserver/docker-compose.yml
docker-compose.yml

For #861 
I've just updated the command in the docker-compose file to update this setting to 1.1 which is typical when running public clouds.  Can be adjusted to 1.5 if the storeage is on the slower side
Also, let me know if you'd prefer to just add a full custom conf file vs the one command and I can update PR

Updated random_page_cost value for postgres

---

common/chat.ts
server/lib/chat/chat-models.ts
server/migrations/20220917093053-remove-password-from-channels.js

We're gonna use an invitation system for private channels, so having a password doesn't make much sense.

Remove password column from the channels table.

---

integration/pages/chat-page.ts
integration/pages/left-nav.ts
integration/pages/login-page.ts
integration/tests/login.spec.ts
integration/tests/signup/different-user.spec.ts
integration/tests/signup/normal.spec.ts
package.json

Move common methods related to the login functionality that are used in the integration tests to the [POM](https://playwright.dev/docs/test-pom).

Introduce POM for integration tests

---

game/src/forge/mod.rs

Instead of having a hook in GetWindowLong and always add the WS_VISIBLE flag in case the GWL_STYLE is queried.
Hook SetWindowLong instead and fixup the flags being passed prior to calling the original SetWindowLong in case it's the SC:R main window.
This fix is required to get Wine working properly, otherwise the Window is left in a hidden state. (Probably because Wine code calls GetWindowLong as well, and the hook is a global trampoline on the DLL code).
Signed-off-by: Jon Doron <arilou@gmail.com>

Game: Forge: Replace GetWindowLong hook with SetWindowLong

---

docs/USEFUL_QUERIES.md

each player in a given time period.

Add a useful query to count the number of matchmaking games played for

---

client/admin/channel-view.tsx
client/chat/action-creators.ts
client/chat/actions.ts
client/chat/channel-menu-items.tsx
client/chat/channel-user-list.tsx
client/chat/channel.tsx
client/chat/chat-message-layout.tsx
client/chat/chat-reducer.ts
client/chat/socket-handlers.ts
client/dom/use-context-menu.tsx
client/icons/material/delete-24px.svg
client/lobbies/lobby-message-layout.tsx
client/material/menu/item.tsx
client/messaging/chat.tsx
client/messaging/common-message-layout.test.tsx
client/messaging/common-message-layout.tsx
client/messaging/mention-hooks.tsx
client/messaging/message-layout.tsx
client/messaging/message-list.tsx
client/parties/party-message-layout.tsx
client/users/user-overlays.tsx
common/chat.ts
server/lib/chat/chat-api.ts
server/lib/chat/chat-models.ts
server/lib/chat/chat-service.ts

A couple of notes:
- doesn't leave a tombstone
- text messages are now highlighted on hover; even if there isn't any
action available on them

Add ability for admins to delete chat messages.

---

client/chat/action-creators.ts
client/chat/actions.ts
client/chat/chat-reducer.ts
client/chat/connected-channel-name.tsx
client/users/connected-username.tsx
server/lib/chat/chat-api.ts
server/lib/chat/chat-models.ts
server/lib/chat/chat-service.test.ts
server/lib/chat/chat-service.ts

Also adds a batch retrieval of user infos in ConnectedUsername.

Add a batch retrieval of chat channels in ConnectedChannelName.

---

client/auth/edit-account.jsx
client/auth/email-verification-notification-ui.tsx
client/auth/email-verification.tsx
client/auth/forgot.jsx
client/auth/login.jsx
client/auth/no-permissions-page.tsx
client/auth/signup.jsx
client/auth/user-error-display.tsx
client/i18n/i18next.ts
i18next-parser.config.json
package.json
server/public/locales/en/global.json
yarn.lock

i18next-parser currently throws an error while trying to generate the translation keys. Will need to figure out what trips it (the stack trace it shows seems fairly useless).

Add translation strings to the auth folder.

---

client/auth/action-creators.ts
client/auth/actions.ts
client/auth/auth-reducer.ts
client/i18n/action-creators.ts
client/material/devonly/radio-test.tsx
client/material/radio.tsx
client/settings/settings-reducer.ts
client/settings/settings-sub-page.ts
client/settings/settings.tsx
client/settings/user/language-settings.tsx
common/users/sb-user.ts
server/lib/users/user-api.ts
server/public/locales/en/global.json

Since the language is changed automatically each time user selects a different option, there is a debounced time of 200ms before we actually make the request. I'm not sure if we should display some kind of an overlay that "disables" the settings until the language is fully changed.

Allow users to change their language in settings.

---

client/file-browser/file-browser.tsx
client/games/results.tsx
client/i18n/action-creators.ts
client/messaging/chat.tsx
client/messaging/common-message-layout.tsx
client/messaging/message-input.tsx
client/network/site-connected-filter.tsx
client/policies/policy-displays.tsx
client/policies/policy-update-notification-ui.tsx
client/replays/browse-local-replays.tsx
client/search/search-input.tsx
client/system-bar/window-controls.tsx
client/users/mini-match-history.tsx
common/games/games.ts
common/games/results.ts
common/maps.ts
common/matchmaking.ts
common/races.ts
common/replays.ts
server/public/locales/en/global.json

Also, reorganize the keys that were added first a bit (mainly removing random keys from the "common" group, and rename "games.results.*" -> "gameDetails.*".

Add translation keys to a few more folders.

---

client/lists/carousel.jsx
client/material/dialog.tsx
client/material/password-text-field.tsx
client/navigation/connected-left-nav.tsx
client/navigation/copy-link-button.tsx
client/navigation/external-link-dialog.tsx
server/public/locales/en/global.json

And a couple of other smaller folders I previously missed (lists and material).

Add translation keys to the navigation folder.

---

client/notifications/action-creators.ts
client/notifications/activity-bar-entry.tsx
client/notifications/notifications-list.tsx
client/notifications/notifications-popup.tsx
client/starcraft/shieldbattery-health.jsx
client/starcraft/starcraft-health.jsx
client/whispers/create-whisper.tsx
client/whispers/nav-entry.tsx
client/whispers/whisper.tsx
common/whispers.ts
server/public/locales/en/global.json

Add translation keys to a notifications, starcraft, and whispers

---

client/landing/top-links.tsx
client/leagues/league-details.tsx
client/leagues/league-explainer.tsx
client/leagues/league-list.tsx
client/logged-out-content.tsx
client/main-layout.tsx
client/root-error-boundary.tsx
server/public/locales/en/global.json

And also rename "league." key prefix to "leagues." to better match feature name.

Add translations to the root folder.

---

docs/USEFUL_QUERIES.md

time period.
By default, the query shows the number of 1v1 matchmaking games in the past 30 days. Includes the dates with 0 games played (so the output can be easily fed into a line chart).

Add a useful query to count the number of matchmaking games in a given

---

client/chat/chat-reducer.ts

Update the client's channel info user count after user joins/leaves the channel.

---

client/chat/channel-header.tsx
server/lib/chat/chat-api.ts
server/lib/chat/chat-service.test.ts
server/lib/chat/chat-service.ts

This enables server admins to change channel settings of official channels too.

Allow server admins to change channel settings.

---

client/games/game-players-display.tsx
client/games/game-reducer.ts
client/maps/maps2-reducer.ts
client/users/action-creators.ts
client/users/actions.ts
client/users/match-history.tsx
client/users/mini-match-history.tsx
client/users/user-profile.tsx
client/users/user-reducer.ts
common/games/results.ts
common/users/sb-user.ts
server/lib/games/game-models.ts
server/lib/users/user-api.ts
server/public/locales/en/global.json

There's no way to filter this list yet. That will come in a future commit.

Add a player's full match history to their public profiles.

---

client/chat/action-creators.ts
client/chat/actions.ts
client/chat/channel-header.tsx
client/chat/channel.tsx
client/chat/chat-reducer.ts
client/chat/socket-handlers.ts
client/material/check-box.tsx
client/material/menu/checkable-item.tsx
client/material/menu/item.tsx
client/material/menu/menu-item-symbol.ts
client/messaging/chat.tsx
common/chat.ts
server/lib/chat/chat-api.ts
server/lib/chat/chat-models.ts
server/lib/chat/chat-service.test.ts
server/lib/chat/chat-service.ts
server/migrations/20231030143012-add-hide-banner-to-channel-users.js
server/public/locales/en/global.json

Also adds an option to users to allow them to hide the banner in case they find it distracting.

Display the channel banner in the channel (behind the messages).

---

client/material/input-base.tsx
client/material/text-field.tsx

Make the multiline TextField padding more consistent.

---

client/material/left-nav/entry.tsx
client/navigation/connected-left-nav.tsx
client/users/user-context-menu.tsx
client/whispers/nav-entry.tsx

A couple of notes here:
- I made the whole nav entry right-clickable, even the X button (this is what Discord does so I thought it's fine).
- I pulled the ConnectedWhisperNavEntry from connected-left-nav.tsx file and put it in whisper's nav-entry.tsx file. It seems more appropriate there to me, and also helps alleviate the length of that connected-left-nav.tsx file, which is substantial. We can do the same for other nav entries in there.
Closed #947

Add user context menu to the whisper nav entry.

---

server/lib/whispers/whisper-service.ts

Add a more defensive code when user closes the whisper session.

---

client/games/game-players-display.tsx

Fixes #885
Preview: 
In the issues thread, 2pac suggested CSS Grid may be the way to do this, but I figured just fixing the placeholders would be less effort

Fix wrap issue

---

docs/UPGRADING_POSTGRES.md

Not sure if this is correct, but it worked for me.

Update the doc for upgrading Postgres.

---

client/dom/auto-size-image.tsx
client/maps/map-preview.tsx
client/material/devonly/slider-test.jsx
client/material/slider.tsx
server/public/locales/en/global.json

Now without using (or changing) the MapInfoImage component.
See commit 1e83d2568f82ab6517046bbc945105a132d95131 for more info.

Add a way to zoom in and pan around map image preview, again.

---

client/replays/replay-info-display.tsx

Fix replay dialog map name getting cut off sometimes.
