.eslintrc, client/lobbies/action-creators.js, server/lib/lobbies/lobby.js, server/lib/wsapi/lobbies.js, server/test/lobbies/lobby.js
This commit fixes all the errors in our lobby tests, as well as
refactors some of the tests to be more readable.
There are also a few more tests added to test some of the edge cases
around the lobbies with observers and hidden slots (UMS-related).
As a part of these lobby tests fixes and improvements, there were a
couple of things changed in our lobby code as well:
- fixed a bug when finding the available slot in observer team
- make the presence of observeres in melee lobbies configurable
- make the observer slots 'closed' by default
Fixes #361
=> Fix and improve lobby tests.

docs/GETTING_STARTED.md
Replaces mentions of shieldbattery.sln/gyp with game.sln/gyp
=> Update the C++ portion of the GETTING_STARTED guide.

app/common/lobbies/index.js, client/actions.js, client/lobbies/action-creators.js, client/lobbies/closed-slot.jsx, client/lobbies/lobby-reducer.js, client/lobbies/lobby.jsx, client/lobbies/open-slot.jsx, client/lobbies/player-slot.jsx, client/lobbies/socket-handlers.js, client/lobbies/view.css, client/lobbies/view.jsx, server/lib/lobbies/lobby.js, server/lib/wsapi/lobbies.js, server/test/lobbies/lobby.js
Some thoughts:
This functionality will delete/add slots in the slot list of a team, which leads to any indices becoming invalidated. It feels fragile, but I didn't see any code which uses something but the slot uids to refer slots. The tests are difficult to follow due to this though.
Additionally, when a slot gets deleted, the server has to obviously send a diff for any slots that were located after the deleted one. On the other hand, diff code hardly had to be changed at all and everything works nicely.
Good? Bad?
=> Allow resizing the observer team

client/activities/activity-overlay.jsx, client/activities/hotkeyed-activity-button.jsx, client/keyboard/key-listener.jsx, client/material/dialog.jsx, client/material/popover.jsx, client/messaging/message-input.jsx
This commit fixes an undesired behaviour with previous version of the
way the `KeyListener` component worked, which was that all of the
registered handlers would get executed for each key event. A situation
where this behaviour is undesired is when for example a dialog is opened
and you could still type in a chat behind it or even open an activity
overlay through hotkeys.
Now some components that use `KeyListener` (activity overlay, dialog and
popover) are marked as `exclusive`, which means when a keyboard event
happens and there is even one registered listener who is exclusive, it
will only execute handlers for that listener and its descendants. The
reason why we need to also execute handlers for descendants is because
activity overlays, dialogs and popovers, can have descendants who …
=> Upgrade the `KeyListener` component to handle exclusive listeners.

client/activities/activity-overlay.jsx, client/lobbies/create-lobby.jsx, client/main-layout.jsx, client/maps/action-creators.js, client/maps/browse-local-maps.jsx, client/maps/browse-server-maps.jsx
So far, the only way to get to the map browser was through 'create lobby'
workflow, which could be used to select a map to host. Now, both the
server and local map browsers have been extended to be able to be used
as a standalone browsers, which will in future allow for more actions on
the maps than the create lobby workflow will allow.
=> Add a standalone map browser available from activity bar.

client/auth/auth-content.jsx, client/material/devonly/text-field-test.jsx, client/material/input-base.jsx, client/material/input-floating-label.jsx, client/material/input-label.jsx, client/material/input-underline.jsx, client/material/select/select.jsx, client/material/text-field.jsx
component.
Multi-line/text area variants can be controlled with 3 properties on a
TextField component:
1. `multiline` prop - turns the TextField into a multi-line one
2. `rows` prop - how many initial lines will be displayed (default: 1)
3. `maxRows` prop - how many lines will TextField expand to before
starting to show a scrollbar (default: 4)
=> Implement a multi-line and text area variants to the TextField

game/Cargo.lock, game/Cargo.toml, game/src/bw_scr.rs
Two different things broke:
1) SNP can no longer be replaced by just writing over global variables.
Now we hook a function that provides SNPs to BW instead.
Predicting future more than that is probably not possible, we'll see if
there are more SNP changes in future
2) The lobby dialog's vtable got a new function, pushing one we have to
implement to be located at a different offset. This could have been made
more resilient by just filling the vtable with this function (as no other
functions are expected to be called), or having more analysis to figure
out the correct offset instead of just hardcoding it.
=> Update for 1.23.3

app/build-native-modules.js, app/native/process/wrapped_process.cpp, app/native/process/wrapped_process.h
This commit also fixes the script that builds our native deps to build
them for the current version of Electron, so there's no mismatch between
node.js versions in Electron and the host environment.
=> Create a minidump file every time the inject fails.

client/beta/splash.jsx
- Fixes the video mime type to match the video file
- Makes the video `cover` instead of `fill`, which avoids distortion at
larger sizes.
- Adds a gradient scrim as a replacement for the opacity the video
previously had, which makes the transition from video -> grey less
abrupt and feels more intentional.
- Reduces the spacing between paragraphs slightly
=> Polish some minor visuals on the splash page.

client/dialogs/connected-dialog-overlay.jsx, client/material/dialog.jsx, client/settings/ipc-handlers.js, client/settings/reducer.js, client/settings/settings.jsx, client/settings/starcraft-path-dialog.jsx, client/starcraft/is-starcraft-healthy.js
Basically, this commit makes setting a StarCraft path a separate
process, upon which the Settings dialog display the settings relevant to
the version of selected StarCraft path.
Currently, the SC:R settings only display a display mode option, which
is not yet hooked into StarCraft itself, but that will come in a
separate PR.
=> Cleanup the settings dialog now that we support SC:R as well.

client/dev.jsx, client/icons/material/chevron_left-24px.svg, client/icons/material/chevron_right-24px.svg, client/lists/carousel.jsx, client/lists/devonly/carousel-test.jsx, client/lists/devonly/routes.jsx, client/lists/infinite-scroll-list.jsx, client/main-layout.jsx, client/material/image-list.jsx, client/material/tabs.jsx
This component can be used as a way to display a list of items, for
example maps. Includes the support for dynamically loading the items
as well, so it can be used as an alternative way to do pagination.
Also, we update the infinite-scroll-list component in this PR, which now
exposes a `hasMoreData` property which can be sent to it to indicate if
there's more data to load. This makes users of this component in charge
of deciding when to stop trying to load more items.
=> Implement a carousel component.

game/Cargo.lock, game/Cargo.toml, game/src/bw_1161.rs, game/src/bw_scr.rs, game/src/bw_scr/pe_image.rs, game/src/bw_scr/sdf_cache.rs, game/src/crash_dump.rs, game/src/forge/mod.rs, game/src/lib.rs
Saves some time on SCR loading. Almost 2 seconds on this slow pc.
The font cache is written to `%APPDATA%\shieldbattery\sdf_cache.dat`, there is also a folder named `Cache` but since it is being used by electron I thought that maybe I should not add any files related to game there.
=> Add a cache for font SDFs

client/active-game/active-game-manager.js, client/lobbies/socket-handlers.js, client/matchmaking/socket-handlers.js, client/replays/action-creators.js, server/lib/games/game-loader.js, server/lib/wsapi/lobbies.js, server/lib/wsapi/matchmaking.js
This should reduce the loading time of SC:R games considerably. Or 5
seconds to be more exact.
Once the countdown finishes, the loading screen is shown for a minimum
of 2 seconds before launching the users into the game.
=> Start loading the game in lobbies as soon as the countdown starts.

client/actions.js, client/active-game/active-game-reducer.js, client/dev.jsx, client/main-layout.jsx, client/matchmaking/accept-match.jsx, client/matchmaking/app-bar-title.jsx, client/matchmaking/devonly/map-selection-test.jsx, client/matchmaking/devonly/match-test.jsx, client/matchmaking/devonly/routes.jsx, client/matchmaking/map-selection.jsx, client/matchmaking/matchmaking-match.jsx, client/matchmaking/matchmaking-reducer.js, client/matchmaking/socket-handlers.js, client/matchmaking/view.jsx, server/lib/wsapi/matchmaking.js
The matchmaking loading process starts once all the players accept the
game, and is executed in the following order:
- The players are moved to the "map selection" screen, where the map
pool for that match is shown and the chosen map is highlighted. That
screen is shown for 5 seconds and then...
- The players are moved to the "countdown" screen, which is counting
down from 5 down to a 0, at which point...
- The `allowStart` command is sent to the game (game process was started
at the beginning of the loading process), and if the game process
didn't manage to start yet, a "Game is starting..." message is shown
to the user until it does, after which...
- The game has fully loaded and the users are shown the "Game in
progress..." message, while being moved to the game to start playing. …
=> Implement the UX/UI of the matchmaking loading process.

docs/GETTING_STARTED.md, package.json, sample.env, server/app.js, server/lib/file-upload/aws.js, server/lib/file-upload/index.js, server/lib/file-upload/local-filesystem.js, server/lib/maps/store.js, yarn.lock
Aws file store can be used by any service that is compatible with
aws-sdk. For now, we're only allowing the usage of DigitalOcean Spaces,
but it shouldn't be much of a problem to support Amazon S3 as well, if
needed.
=> Add a basic implementation of an Aws file store.

client/maps/map-thumbnail.jsx, client/maps/maps-reducer.js, server/lib/api/maps.js, server/lib/maps/map-parse-worker.js, server/lib/maps/store.js, server/lib/models/maps.js
This PR assumes we're only gonna generate two images for each map, so
it doesn't bother making the code too generic to work for N amount of
images. That seems like a reasonable assumption for now. If it ever
breaks, some kind of an array format will need to be used to work with
the image URLs, and their saving path might need to be rethought.
=> Generate a smaller sized image for all maps and use it as a thumbnail.

client/lobbies/loading.jsx, client/lobbies/lobby-reducer.js, client/lobbies/lobby.jsx, client/lobbies/view.jsx, client/maps/browse-server-maps.jsx, client/maps/map-image.jsx, client/maps/map-preview.jsx, client/maps/map-select.jsx, client/maps/map-thumbnail.jsx, client/maps/maps-reducer.js, client/matchmaking/matchmaking-match.jsx, server/lib/api/maps.js, server/lib/file-upload/local-filesystem.js, server/lib/maps/map-parse-worker.js, server/lib/maps/store.js, server/lib/models/maps.js
displaying map images.
Also uses it throughout the app. There are two components that are a
level higher than MapImage component, which are MapThumbnail and
MapPreview. They can be used in places where some common functionality
is required to make things easier (though MapPreview is pretty bare
atm).
This PR also updates the naming scheme of the map image names and URLs
to be a bit more cleaner and consistent. They are also saved in the same
folder now.
=> Create a MapImage component that should be used as a primitive for

client/material/input-base.jsx, client/material/text-field.jsx
I noticed it was possible to highlight text inside of text-fields in Chrome, but not in Firefox.
I used inherit for input-base so that it did not allow highlighting text in select components.
=> Fix textfield highlighting in Firefox

.editorconfig, client/active-game/active-game-manager.js, client/active-game/game-server.js, client/lobbies/socket-handlers.js, client/matchmaking/socket-handlers.js, common/game-status.js, game/Cargo.lock, game/Cargo.toml, game/src/app_messages.rs, game/src/game_state.rs, game/src/game_thread.rs, server/lib/api/gameResults.ts, server/lib/models/games-users.ts, server/lib/models/games.ts, server/lib/validation/joi-validator.ts, server/websockets.js
This sets things up so we can make this request from the Rust code, as the game finishes. We make 3 attempts, if all 3 fail, the expectation is that the app will retry at some point in the future (but this is NOT implemented yet as of this PR). The app can know to do this by the fact that the game exits without calling `/game/resultSent` (and my plan is to always submit some sort of results if that occurs, to try to give us fewer result timeouts in the case of weird issues).
APM calculation is also not included in this PR, for now everybody is registered as having 0 APM.
Note that there's a number of random Rust reformatting changes in here, as VSCode really wanted to do them. I adjusted our `.editorconfig` to preserve most of the existing formatting.
=> Send the game results to the server on game end.

client/app.jsx, client/index.jsx, package.json, server/routes.js, server/views/index.jade, yarn.lock
This commit removes the Google Analytics integration we had (though it
didn't even work since last react-router upgrade anyway). It's
questionable how useful GA would be to us, and not integrating it has a
nice bonus that we now don't need to add a cookie consent form.
Closes #387
=> Remove GA.

game/Cargo.lock, game/Cargo.toml, game/build.rs, game/compile-shaders/Cargo.toml, game/compile-shaders/src/lib.rs, game/scr-analysis/Cargo.toml, game/scr-analysis/src/lib.rs, game/src/bw.rs, game/src/bw/list.rs, game/src/bw/unit.rs, game/src/bw_1161.rs, game/src/bw_scr.rs, game/src/bw_scr/shader_replaces.rs, game/src/bw_scr/shaders/mask.hlsl, game/src/bw_scr/thiscall.rs, game/src/game_state.rs, game/src/game_thread.rs
Unexplored areas are displayed slightly darker than obscured but FoW'd
ones. Resources/neutral units still display in unexplored areas. This
functionality is disabled for UMS games.
Also adds shader hot reloading support to debug builds.
=> Replace SC:R mask shader with one that shows unexplored areas.

client/active-game/active-game-manager.js, game/src/app_messages.rs, game/src/game_state.rs
I guess it's fine to not have the game send results to app either when watching a replay? App seems to not rely on receiving results before end message atm.
Closes #574
=> Don't send game results when watching a replay

app/app.js
It seems that there is a bug in Electron which makes it not emit 'focus'
event anymore when the application is closed to system tray. The 'show'
event is emitted fine so we use that.
=> Clear the unread notification icon on the 'show' event as well.

client/app.jsx, client/auth/action-creators.ts, client/auth/actions.ts, client/auth/auth-reducer.ts, client/auth/email-verification-notification.jsx, client/auth/email-verification.jsx, client/main-layout.jsx
Instead, show the success/failure of the action in a snackbar.
Fixes #585
=> Don't open a new page when resending a verification email.

server/lib/models/user-ips.ts, server/lib/network/user-ips-type.ts, server/lib/websockets/socket-groups.ts
to user's socket manager.
This allows us to import socket-groups file in tests without also
importing the file that checks whether the database environment variable
is properly set up.
=> Use tsyringe to inject "updateOrInsertUserIp" function as a dependency

client/active-game/game-config.ts, client/lobbies/lobby-reducer.js, game/Cargo.toml, game/build.rs, game/scr-analysis/src/lib.rs, game/src/app_messages.rs, game/src/bw.rs, game/src/bw_1161.rs, game/src/bw_scr.rs, game/src/game_state.rs, game/src/game_thread.rs, game/src/hook_macro.rs, game/src/lib.rs, game/src/replay.rs, game/src/windows.rs, game/src/windows/version.rs
This adds support for expanding SC:R replays with custom data.
The SC:R replay format already has support for custom sections of data that can be skipped over by users that don't understand the section, so this will just append one more section at the end when the replay is being saved.
Also, as such, 1.16.1 replays don't change at all, maybe it can be patched to support SC:R replays in general if needed? Eventually.
The currently saved data & its format is very simple, uncompressed binary format, contains SC:R patch, shieldbattery version(*), and few bytes that fix team melee replays.
And a version id for future changes. Maybe there would be value in having some "better" format that is trivial to extend without breaking backwards compatibility for future before merging this PR? Though …
=> Extend new replays with extra data

client/file-browser/browse-files.jsx, client/maps/browse-local-maps.jsx, client/replays/watch-replay.jsx
File browser now accepts an array of root folders which you can change
when displaying particular browser through a dropdown. If there's only
one root folder sent to the browser, the dropdown is not shown.
=> Allow setting multiple root folders in a file browser.

game/Cargo.toml, game/scr-analysis/Cargo.toml
The following error arised
```bash
Updating git repository `https://github.com/neivv/samase_scarf/`
error: failed to get `samase_scarf` as a dependency of package `scr-analysis v0.1.0 (E:\Prog\ShieldBattery\game\scr-analysis)`
Caused by:
failed to load source for dependency `samase_scarf`
Caused by:
Unable to update https://github.com/neivv/samase_scarf/?rev=39c6665a423a84d0f20ac03306ce0bd21def1c35#39c6665a
Caused by:
failed to clone into: C:\Users\Coincoin\.cargo\git\db\samase_scarf-70e8ba1a878083d4
Caused by:
process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/neivv/samase_scarf/' 'refs/heads/*:refs/remotes/origin/*' 'HEAD:refs/remotes/origin/HEAD'` (exit code: 128)
--- stderr
ERROR: Repository not found.
fatal: Could not read from remote …
```
=> Fix custom Github dependencies path for samase_scarf and whack.

server/lib/maps/map-parse-worker.js
Original code has a typo mistake with `const code = c.charCodeat(0)` instead of `const code = c.charCodeAt(0)`.
In my environment (node version is v14.15.5) , this leads to the below error if using `charCodeat`.
```
TypeError: c.charCodeat is not a function
at E:\Prog\ShieldBattery\server\lib\maps\map-parse-worker.js:94:22
at Array.filter (<anonymous>)
at filterColorCodes (E:\Prog\ShieldBattery\server\lib\maps\map-parse-worker.js:93:6)
at E:\Prog\ShieldBattery\server\lib\maps\map-parse-worker.js:140:18
at new Promise (<anonymous>)
at process.<anonymous> (E:\Prog\ShieldBattery\server\lib\maps\map-parse-worker.js:136:25)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
Assertion failed
[2021-03-05 21:38:14.592 +0000] ERROR (17048 on Canard): server error
err: {
"type": …
```
=> Fix correct typo for charCodeAt call

docs/GETTING_STARTED.md
There is no `package.json` file in the `server/` folder, `yarn start` cannot be available, I suppose it is legacy. 
Both proposed commands worked for me from project directory:
```
yarn run start-server
```
```
node ./server/index.js
```
=> Rectify run server commands. Clarify how to get MQP files.

app/settings.js, client/settings/settings-records.js
Those defaults get passed to SC:R if there isn't anything else
specified, and at least sdGraphicsFilter being -1 straight up crashes.
=> Don't use -1 as a default for SC:R settings

client/matchmaking/find-match.jsx, server/lib/api/matchmakingPreferences.ts, server/lib/wsapi/matchmaking.ts
=> Matchmaking for random race

client/lobbies/race-picker.jsx, client/lobbies/selected-race.jsx, client/matchmaking/find-match.jsx
I figured it looked a bit odd that you could select your alternate race to be the same as your main race.
Preview:
=> Hide alternate race icon that matches selected main race

client/chat/channel.tsx, client/chat/chat-message-layout.tsx, client/chat/chat-message-records.ts, client/chat/chat-message-records.tsx, client/chat/chat-reducer.js, client/lobbies/lobby-message-layout.tsx, client/lobbies/lobby-message-records.ts, client/lobbies/lobby-message-records.tsx, client/lobbies/lobby-reducer.js, client/lobbies/lobby.tsx, client/messaging/message-layout.jsx, client/messaging/message-list.tsx, client/messaging/message-records.ts, client/react-extra-hooks.ts, client/state-hooks.ts, client/whispers/whisper-reducer.js
This is the first (out of many I'm sure) steps that refactors the chat
stuff to make it more organized and with less repetitions. This PR
organizes and refactors a bunch of stuff related to message types.
The idea was simple:
- Everything that is common to all messaging-related services (chat,
whispers, lobbies, parties) should go in the "messaging" folder
- Everything else that's specific to a particular message service goes
in their respective folders
So related to the message types, in the messaging folder there's only
basic text message type defined that's used in all the services, while
chat and lobbies (whispers don't have any yet) specific message types
are defined in their own folder.
Besides definition of message types, this PR applies the same principle
for messages layout as …
=> Refactor the handling of chat message types.

client/activities/activity-button.tsx
Fixes #532 
Underlines the first character of the label that matches its hotkey button.
Always shows, even if its modifier key is not pressed.
Preview:
=> Add underline to activity buttons

client/file-browser/get-files.js
Closes https://github.com/ShieldBattery/ShieldBattery/issues/239. I figured the improved logging route would be better since this would effect more than looking up replays (I think) and on a good broodwar install the folder should be there anyway.
=> Make missing filepath error more clear

server/app.ts
If you have a bad redis password or host, you'll see the log message without any other indication of failure. 
```
{"level":30,"time":1622497667609,"pid":18068,"hostname":"DESKTOP-8GER2KL","req":{"id":"ckpd57vxc0002xwuxcvya3agl","method":"GET","url":"/__webpack_hmr","headers":{"host":"localhost:5555","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0","accept":"text/event-stream","accept-language":"en-US,en;q=0.5","accept-e
ncoding":"gzip, deflate","connection":"keep-alive","referer":"http://localhost:5555/ladder","cookie":"s=ckpa49sxs001o1suxcaiz0h49; s.sig=4sSvYlKGhsYLrBQm-RfWH0zT4C8","pragma":"no-cache","cache-control":"no-cache"}},"res":{"statusCode":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with …
```
=> Kills server on bad redis connection

server/lib/api/bans.js, server/lib/chat/chat-api.ts, server/lib/chat/chat-service.ts, server/lib/models/whispers.js, server/lib/parties/party-service.ts, server/lib/websockets/socket-groups.ts, server/lib/wsapi/lobbies.js, server/lib/wsapi/matchmaking.ts, server/lib/wsapi/whispers.js
All other services have only been updated by a bare minimum to make them
work again. Subsequent PR(s) should update them to use the `userId`s as
well, to make things more internally consistent and easier to work with.
=> Move the user sockets to use primarily `userId` instead of `userName`.

.gitignore, server/lib/db/index.ts, server/lib/db/pg-error-handler.ts
This is still a work in progress but wanted to share some work because I have some questions. 
1.) I've been googling everywhere and I can't find a way other than using something like https://www.npmjs.com/package/verror to get a full stack trace from where the query is made back to where it's parsed. I'm not sure if it's a super big deal though. 
2.) I kind of dislike relying on postgres' convention of using the first two values of the error code to show what class the error is. Would typing the errors by class, or building an enum of classes be overkill?  I don't think most error types will require a ton of customization 
3.) I was kind of thinking that hijacking the reject error of the Promise returned by the wrappedclient to do the parsing, and letting the caller handle it properly …
=> Handle pg syntax error

client/profile/user-reducer.ts, client/whispers/action-creators.ts, client/whispers/actions.ts, client/whispers/socket-handlers.ts, client/whispers/whisper-reducer.ts, common/whispers.ts, server/lib/whispers/whisper-models.ts, server/lib/whispers/whisper-service.ts
Whispers are kind of in a weird place because we still want to use the
usernames in all the routing-related paths, which means it's still
preferable to use the usernames in various data structures (e.g. in the
reducer).
To be honest, we could probably get away with using usernames everywhere
(which makes this PR kinda useless huh), since we only need user IDs in
a couple of places, like in each whisper message.
=> Move the whispers stuff away from using usernames internally.

client/parties/actions.ts, client/parties/party-reducer.ts, client/parties/party-view.tsx, client/parties/socket-handlers.ts, server/lib/parties/party-service.test.ts, server/lib/parties/party-service.ts, server/lib/websockets/testing/websockets.ts
This can happen when a user gets invited to a party while they were
already in a different party. By accepting the invite to a new party,
they will immediately leave the old party and be put in a new party.
TODO: The transition from one party to another might be a bit jarring,
so maybe eventually we want to display some kind of a confirmation
dialog before doing it?
=> Handle user changing a party.

client/notifications/socket-handlers.ts, server/lib/parties/party-service.test.ts, server/lib/parties/party-service.ts, server/lib/websockets/testing/websockets.ts
This PR does two things:
- doesn't display party invite notifications on web clients
- throws an error if user tries to accept a party invitation on a
non-electron client
=> Improve the party handling on non-electron clients.

client/parties/actions.ts, client/parties/party-message-layout.tsx, client/parties/party-message-records.ts, client/parties/party-reducer.ts, client/parties/party-view.tsx, client/parties/socket-handlers.ts, common/parties.ts, server/lib/parties/party-service.test.ts, server/lib/parties/party-service.ts
Generally the person who has joined the party the earliest will be
chosen as a new leader, but there's no robust solution implemented that
ensures this. My thinking was that since the multiple invites can be
sent at once, and the order in which those invites are accepted are
pretty arbitrary already, there's really no reason why someone
"deserves" to be a new leader more than someone else. Or well, no reason
big enough to spend time implementing a robust solution for this at
least :)
=> Assign new leader in a party when the old one leaves.

client/navigation/connected-left-nav.jsx, client/parties/action-creators.ts, client/parties/actions.ts, client/parties/party-nav-entry.tsx, client/parties/party-reducer.ts, client/parties/socket-handlers.ts, common/parties.ts, server/lib/notifications/notification-model.ts, server/lib/notifications/notification-service.ts, server/lib/parties/party-service.test.ts, server/lib/parties/party-service.ts
This PR does the following:
- don't emit the "decline" event to the party when someone declines an
invite
- don't display an error in snackbar if decline fails (these errors are
mostly not of interest to the decliner)
- don't throw an error when inviting someone who is already invited
(this would reveal to the party the the user has declined the first
invite)
- only send invite notification if one already doesn't exist that is
visible
- don't remove user from the invited users list if they decline
=> Improve the handling of the "decline invite" logic in parties.

client/parties/action-creators.ts, common/parties.ts, server/lib/errors/error-with-payload.ts, server/lib/parties/party-api.ts, server/lib/parties/party-service.ts
These are more or less the only errors that are likely to happen to
users in their normal usage of the party system. Now we display the
actual reason to them if they try to accept an invite to a party that
doesn't exist anymore, or if the party is currently full.
=> Display the actual reason why accepting a party invite failed.

client/messaging/common-message-layout.tsx, common/text/links.test.ts, common/text/links.ts
This does some basic link detection in text messages, similar to what
Discord does. One thing that should probably be added as soon as
possible as well is some kind of a warning message that we show to users
about opening untrusted links.
But then we should also probably remember their choices for each
specific domain, and that's a whole thing now ^^.
Additionally, the component that is implemented here to parse the text
messages could be extended to parse other types of content (e.g.
mentions, links to lobbies, maps, etc.). Regex for each of those should
be written separately, which should be easier since we can create custom
schemes for each one, and then combined into a single regex so the text
is parsed only once. I don't know yet if this is possible or how it will
work, but we'll see …
=> Detect links in text messages and make them clickable.

client/matchmaking/find-match.jsx
to true.
Previously we would send `useAlteranteRace` to server, whatever it was
previously set. And with a main race set to random, this would case an
error when saving matchmaking preferences. Now we're forcing
`useAlternateRace` to `false` whenever main race is set to random.
=> Fix a bug when selecting a random race while `useAlternateRace` was set

server/lib/maps/map-models.ts
It was broken from DB changes in b30e014a69b4626771893094d98695281142c613.
=> Fix deleting all maps

client/messaging/common-message-layout.test.tsx, client/messaging/common-message-layout.tsx, common/text/mentions.test.ts, common/text/mentions.ts, server/lib/messaging/process-chat-message.ts
When having two mentions separated by a space, the "postfix" character
of the first mention would interfer with the "prefix" of the second
mention, resulting in second mention not being mentioned.
This was fixed by making the "postfix" group use the positive lookahead
instead of a named capture group, so it doesn't end up in matched
string.
Also added a regression test for this behaviour.
=> Fix the mention regex not matching multiple mentions separated by space.

client/maps/devonly/maps-for-testing.ts, common/maps.ts, game/src/app_messages.rs, game/src/bw.rs, game/src/bw_1161.rs, game/src/bw_scr.rs, game/src/game_state.rs, package.json, server/lib/lobbies/lobby.test.ts, server/lib/maps/map-models.ts, server/lib/maps/map-parse-worker.js, server/lib/maps/parse-data.ts, server/migrations/20211109203236-add-eud-map-column.js, yarn.lock
Does not include anything to parse existing maps again, so this won't fix
EUD maps that were already uploaded.
The bw-chk update also adds support for UTF-8 map encodings; this also
would benefit from being able to reparse all maps in the database.
=> Support EUD maps

client/chat/actions.ts, client/chat/chat-reducer.ts, client/chat/socket-handlers.ts, common/chat.ts, server/lib/chat/chat-models.ts, server/lib/chat/chat-service.ts, server/migrations/20211110231126-add-channel-owners.js
Currently, we were using the "edit_permissions" flag as a makeshift
indicator of channel ownership. However, this is not ideal since more
than one person can have this permission set. Technically we could've
defined a channel owner at the model level, where the owner would be set
as a user with this permission and who joined the channel the earliest.
However, I feel like this would get a bit unwieldy and messy down the
line, especially if we start thinking about features like transferring
channel ownership.
This PR adds another column to the database, which ensures that there
can be only one owner per channel, at the database-level. I guess it is
a little bit weird to have a flag that trumps all other flags, no matter
their values, but I believe this is what Discord does too, so we should …
=> Make channel owners be defined explicitly, instead of implicitly.

client/chat/action-creators.ts, client/chat/actions.ts, client/chat/channel.tsx, client/chat/chat-reducer.ts, client/chat/socket-handlers.ts, client/profile/user-reducer.ts, common/chat.ts, server/lib/chat/chat-api.ts, server/lib/chat/chat-models.ts, server/lib/chat/chat-service.ts, server/migrations/20211118224131-rename-joined-channels-table.js
This PR also does a couple of other things:
- cleans up most of the chat event types to only use `userId` instead
of a whole channel user object if possible
- renames the `joined_channel` table in the DB to `channel_users`
=> Send user their channel permissions when they join a channel.

app/app.ts
This does the same thing as Ctrl+R in our app, but muscle memory is a
helluva thing.
=> Register the Ctrl+Shift+R hotkey as well.

app/game/native/process/wrapped_process.cpp
Unfortunately I have no idea how to or interest in trying make node-gyp work with whatever issue I have with it now, so this may not even compile yet :l
1) There was a race where worker thread could finish the work before
parent started its wait -- kind of obvious in hindsight due to parent_lock
not protecting anything.
2) Multiple parents trying to run task on worker thread would cause tasks
to be lost since there was only one task available. Usually not a problem
since having app manage multiple processes doesn't happen almost ever,
but if it happened due to first bug or something else, the app would
completely break.
=> Fixes to native process worker thread task code

.eslintrc, client/dom/unique-id.ts, client/material/button.tsx, client/material/devonly/routes.tsx, client/material/devonly/tooltip-test.tsx, client/material/popover.tsx, client/material/portal.tsx, client/material/tooltip.tsx, client/messaging/message-layout.tsx, client/profile/user-profile-overlay.tsx, client/styles/colors.ts
overlay join date and chat message timestamp.
There are a few issues remaining that I haven't figured out how best to
resolve yet:
- Tooltip open state tracking needs to be reworked. Using simple
mouseenter/mouseleave events to track the Tooltip open state is not
good enough. For example, it's possible for Tooltip to be displayed
above its target element (in case of popover clamping at the edge of a
screen for example), in which case the 'mouselave' event of the target
element is triggered if the Tooltip is shown right below the mouse
cursor.
Also, there's some weirdness when Tooltip is opened above one element
that also has a Tooltip and then moving the mouse over that element
quickly can show/hide its Tooltip immediately. This is most easily
reproducible on hovering over chat message …
=> Add a Tooltip component and use it to display full dates in user profile

client/icons/codicons/chrome-restore.svg, client/system-bar/window-controls.tsx
I must be the only person who uses the app in maximized state and get
ticked off by icon being the same in both maximized and non-maximized
states ^^.
This might've been a bit cleaner to implement if we saved the maximized
state in the store, but hopefully this is good enough for now.
=> Use a restore icon when the window is maximized.

client/chat/chat-reducer.ts, client/chat/socket-handlers.ts, common/chat.ts, server/lib/chat/chat-models.ts, server/lib/chat/chat-service.ts, server/migrations/20220228141557-move-channel-owners-to-channels-table.js
Even though it makes retrieving some information a bit harder, having
the owner state in the channels table itself just makes a lot more sense
than having it in channel_users table. Also, this ensures that there is
only one owner per channel, and makes changing user permissions a bit
safer.
=> Move the channel owners state to the channel table itself.

client/admin/map-pools.jsx, client/lobbies/slot-actions.tsx, client/maps/browser-footer.tsx, client/maps/map-thumbnail.tsx, client/material/devonly/menu-test.tsx, client/material/menu/item.tsx, client/material/menu/menu-item-symbol.ts, client/material/menu/menu.tsx, client/material/menu/selectable-item.tsx, client/material/menu/selected-item.tsx, client/material/select/option.tsx, client/material/select/select.tsx, client/navigation/connected-left-nav.tsx, client/users/user-context-menu.tsx
Now the menu component only renders its contents and it's left to the
users of this component to render it inside a popover, if they wish so.
The reason for this separation is so we can have menus that need to
run certain hooks (e.g. connect to a store) to only do so if they're open.
This commit also does the following:
- change the handling of the selectable menu items
- fix the scrollable menu (the menu items would shrink and not show
the scrollbar)
- fix the focused state of the menu items by using the button's
native focus state instead of faking it
- remove the TAB hotkey (not sure what this hotkey should be doing in
the first place)
- add the SPACE hotkey to click the menu item (along with ENTER)
- stop scrolling the menu to the selected item when first opened; i'm
not sure if this …
=> Refactor the menu component to not render the popover part.

server/lib/maps/map-api.ts
For #786 
Just removed the offending if statement. 
Test suite runs successfully and I've been able to edit / update a map without description without issue.  
Was able to create a game with that map and play with no issues.
=> Removing bad request error for empty map description

client/file-browser/file-browser-entries.tsx, client/file-browser/file-browser.tsx, client/replays/browse-local-replays.tsx
- remove the dropdown button
- clicking the file entry open/closes the panel
- only one file entry allowed to be open at a time
- remove the redundant action button inside the panel itself
- left-align the replay info inside a centered container
- make the spacing between the replay info text consistent
Screenshot:
=> Improve the file expansion panel user experience and design.

common/chat.ts, server/lib/chat/chat-models.ts, server/lib/chat/chat-service.ts, server/migrations/20220917094539-rename-channels-high-traffic-column.js
Official channels have the following characteristics:
- they're created by staff members only
- they don't have owners (so only server moderators can moderate them)
- they're not deleted when everyone leaves (thus keeping the message history in perpetuity)
- TODO MAYBE: join/leave messages are not shown in them
- TODO MAYBE: new accounts are automatically joined in all (some?) of them
TODO: Currently, every channel that is created is a non-official channel (except ShieldBattery which was created as an official channel in a migration), so once we make it possible to update channel settings, we gotta make sure to set the channel owner to NULL if the channel is being made into an official channel. I don't think it's that big of a deal even if we don't, since only staff will most likely be …
=> Rename the "high_traffic" column to "official" in the channels table.

client/admin/map-pools.jsx, client/lobbies/slot-actions.tsx, client/maps/browser-footer.tsx, client/maps/map-thumbnail.tsx, client/material/devonly/menu-test.tsx, client/material/devonly/popover-test.tsx, client/material/popover.tsx, client/material/select/select.tsx, client/navigation/connected-left-nav.tsx, client/navigation/lockup.tsx, client/notifications/activity-bar-entry.tsx, client/users/friends-list.tsx, client/users/nav-entry.tsx, client/users/self-profile-overlay.tsx, client/users/user-overlays.tsx
And use it in all Popover usages.
This hook makes sure that there's only one Popover opened for the same source event.
Also, inadvertently fixes #771 and other places where we used the same open/onDismiss state for different Popovers.
=> Add a hook which tracks the Popover open state.

.github/workflows/tests.yml, server/lib/chat/chat-service.ts
This commit also introduces a typescript error which will be used to check if the failure check works. Will remove the error in the next commit if it does.
=> Make the GitHub actions failure check more specific.

server/lib/chat/chat-models.ts, server/lib/users/user-identifiers.ts
I've checked all of our usage of INSERT INTO statements, and these were the only two places that used an implicit column order. Which just seemed like a bug waiting to happen.
And in fact it did happen in chat banning case.
Fixes #894
=> Use an explicit column order in INSERT INTO statements.

client/lists/infinite-scroll-list.tsx
messages.
The problem was when the initial state of `hasPrevData`/`hasNextData` was `false` (or `undefined`), which was the case in receiving the `chatReady` event *before* the chat `init` event. So we would start rendering the channel and channel messages with the default state and `hasMoreHistory` would be `undefined`. This meant that the inifnite-scroll-list would not render the observing element (i.e. LoadingArea) and nothing would be observed.
Once we've received the `init` event and `hasMoreHistory` would become `true`, the observing element would finally render, but there was nothing in the infinite-scroll-list that would try to observe the element again, and it would get stuck like that. Now the infinite-scroll-list automatically restars observing if `hasPrevData`/`hasNextData` …
=> Fix a bug in infinite-scroll-list which would sometimes not load chat

client/chat/chat-reducer.ts, common/chat.ts, server/lib/chat/chat-service.test.ts, server/lib/chat/chat-service.ts
This removes any potential weirdness between interleaving `chatReady` and `init` events. Now `chatReady` event is sent when the user first connects to the server, and `init` event is sent when the user joins a new channel.
=> Include the full initial channel data in the `chatReady` event.

client/starcraft/shieldbattery-health.jsx, common/flags.ts
I noticed this  while looking at replays while running locally. I ran into it because I hadn't run game/build.bat
I'm not sure if throwing is too aggressive here, I could use a similar dialog as a normal installation issue.
=> Throws error in development if game hasn't been built

client/auth/login-layout.tsx, client/i18n/i18next.ts, client/landing/top-links.tsx, common/flags.ts, common/i18n.ts, package.json, server/public/locales/en/global.json, yarn.lock
out users.
The detected language is first detected from the "navigator" settings and saved into the local storage and is not currently being sent to the server during the signup process. That will come in the next commit.
User can change the language on all of the pages that render top-links; basically splash/faq/login/signup.
=> Add automatic language detection and a way to change language for signed

client/settings/game/gameplay-settings.tsx, client/settings/game/input-settings.tsx, client/settings/game/sound-settings.tsx, client/settings/game/video-settings.tsx, client/settings/settings-content.tsx, client/settings/settings.tsx
- Move the Close button into its own column and increase its size
- Lower the max-width from 960px -> 840px
- Make all of the setting pages a single column
- Add/remove spacers where it made sense (probably botched this one)
Closes #945
=> Improve the settings visuals.

client/chat/socket-handlers.ts, common/chat.ts, server/lib/chat/chat-api.ts, server/lib/chat/chat-service.test.ts, server/lib/chat/chat-service.ts, server/lib/errors/coded-error.ts, server/lib/games/game-loader.ts, server/lib/parties/party-service.ts, server/lib/session/session-api.ts
The previous code could produce a bug in a following case:
- connect with one client to the server and create a channel
- connect with the second client to the server
- second client will receive both the `chatReady` and `init3` events in the non-consistent order (depends on how things execute on the server)
- if the second client receives the `init3` event before the `chatReady` event, their channel list will be out of order
This fix makes it so we don't send the `init3` event when they connect to the server, but only immediatelly after they join a channel.
Additionally, we could also change the reducer on the frontend to always rewrite the channel list when it receives the `chatReady` event, but it seems unnecessary to me.
=> Fix the issue where the channels can potentially end up in wrong order.

client/chat/admin/channel-content.tsx
channel.
When the last person leaves a non-official channel, it gets deleted. However, there might've been some channel banners which were available in this now-deleted channel, so we can't display its name in the channel banner card.
Note that this still leaves the deleted channel in the banners table in DB, so an ideal fix would be where each `channelId` in the `available_in` column in the `channel_banners` table is a foreign key to the `channels` table. Is that even possible? :/
Although this also might leave things in a weird state, where a channel banner is marked as `limited`, but doesn't have any channel that it's available in.
=> Fix the channel banner card trying to display a name of the deleted

client/i18n/action-creators.ts, client/i18n/i18next.ts, client/i18n/language-detector.test.ts, client/i18n/language-detector.ts, client/index.jsx, package.json, yarn.lock
i18n's version had some very weird rules, so we just implement our own now. Fairly rudimentary at the moment, and I'm sure it doesn't cover *all* of the possible language codes, but should work for our supported languages.
Fixes #1051
=> Implement our own version of the language detector.

client/file-browser/file-browser.tsx, client/replays/browse-local-replays.tsx
For folders we're using a reverse-alphabetical order since that's what Battle.net seems to be doing and people are used to it.
Also, this will matter less once we make the sort order customizable.
=> Change the default replays sort order to be most recent stuff first.

client/chat/channel-header.tsx, client/material/popover.tsx, client/material/tooltip.tsx
Interactive tooltips allow users to interact with the content inside it, e.g. pressing buttons and links.
Also, we're utilizing this interactive tooltip for the topic in channel header.
Closes #1007
=> Add the option to make Tooltip interactive.

client/chat/channel-list.tsx
This fixes a bug that could've happened if the previous request was still loading, the new one wouldn't be executed because infinite-scroll-list only runs the load more data callback if it's not already loading.
This is a band aid fix; the proper fix would involve fixing infinite-scroll-list, but is also a bit more work so this will have to do for now.
=> Fix a bug in channel list search leading to potentially not searching.

client/material/input-base.tsx, client/material/text-field.tsx
Also fixes a bug which wouldn't render the correct size of textarea if the initial value was causing it to have multiple rows.
Fixes #1068
=> Fix the spacing/padding issues in multiline TextFields.

.github/workflows/server-rs-ci.yml, client/lobbies/socket-handlers.ts, server/lib/wsapi/lobbies.js
So there are 2 issues that were happening in the previous code when user would leave the lobby:
- We would publish the `cancelLoading` event only to the user who left, instead of the whole lobby.
- We would delete the lobby from the loading state only in case everyone left, instead of always.
I made the loading cleanup a bit more consistent now and similar to how/when cancel countdown happens. The only slightly weird thing here is that we publish the event to the lobby list to add the lobby back to the list when the loading gets canceled. However this is also done when cleaning up the countdown state as well, so we have two events fire each time, because those two cleanup functions are called in unison. We could perhaps combine these two functions into one, but I don't think it's a big …
=> Properly clean up state when users leave during countdown/loading.

client/landing/top-links.tsx, server/public/locales/en/global.json
How it looks like now:
Closes #994
=> Include current language in top links' language picker button.

client/users/user-context-menu.tsx
Returning a new array each time the selector is called is causing a redux warning. And it's probably not that great for performance either or whatever.
=> Split the relationship selector into two to get rid of redux warning.

package.json, pnpm-lock.yaml, sample.env, server/lib/file-upload/aws.ts, server/lib/file-upload/index.ts, server/lib/maps/store.ts
Aws sdk v2 has been deprecated:
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/
Even though there's still a year until the end-of-support, I thought I'd be proactive and update to v3 now.
This was mostly done by running their codemod and fixing a couple of issues manually, e.g.
`npx aws-sdk-js-codemod -t v2-to-v3 ./server/lib/file-upload/aws.ts`
One thing I have *not* done yet is setup DO spaces to be use locally which would actually test this code. That seems like a pretty important step tho :d. However, in my defense, setting up that locally is a hassle and I forgot how to do it, so we can just leave this in open PR now until that is done.
=> Update aws-sdk to v3.

client/chat/action-creators.ts, client/games/action-creators.ts, client/network/request-coalescer.ts, client/users/action-creators.ts, client/users/user-reducer.ts, common/async/abort-signals.ts
I think I got all of our usages with this? Ended up being fewer than I initially thought.
Also, while searching for these usages, I've deleted a few unused states from the user's reducer.
Closes #1101
=> Add a helper class to simplify the usage of the `BatchedAbortSignals`.

client/messaging/message-list.tsx, client/users/user-profile-overlay.tsx, client/whispers/whisper.tsx
Also adds an empty state for the message list component. I guess it could potentially be useful to show a different empty message in different chat contexts, but this is mostly only relevant in the whispers page anyway. In all other chat contexts we have so far, we pretty much always have at least one message showing.
Closes #1099
=> Show target user profile info in the whisper page.

client/file-browser/file-browser-entries.tsx, client/file-browser/file-browser.tsx
This is mostly useful if you click on Watch Replay button without focusing that replay entry first. The replay would start fine, but the file entry would not be focused, confusing you what was the last replay you watched.
I couldn't just remove the `event.stopPropagation()` on the Watch Replay button, because that would also expand the replay info panel as well as started the replay.
=> Focus the replay entry in the file browser when Watch Replay is clicked.

client/ladder/devonly/table-test.tsx, client/matchmaking/find-match.tsx, client/matchmaking/matchmaking-seasons-reducer.ts, client/users/action-creators.ts, client/users/actions.ts, client/users/match-history.tsx, client/users/user-profile-seasons.tsx, client/users/user-profile.tsx, client/users/user-rank-display.tsx, common/ladder/ladder.ts, common/users/sb-user.ts, server/lib/ladder/ladder-api.ts, server/lib/matchmaking/models.ts, server/lib/users/user-api.ts, server/public/locales/en/global.json
The ranking history is displayed under the "Seasons" tab and only includes past seasons in which user had a rank. Doesn't include the current season.
Closes #1107
=> Display user's ranking history in their profiles.

client/ladder/action-creators.ts, client/ladder/devonly/table-test.tsx, client/ladder/ladder-reducer.ts, client/ladder/ladder.tsx, client/matchmaking/action-creators.ts, client/matchmaking/actions.ts, client/matchmaking/matchmaking-seasons-reducer.ts, common/matchmaking.ts, server/lib/ladder/ladder-api.ts, server/lib/matchmaking/matchmaking-api.ts, server/lib/matchmaking/models.ts, server/public/locales/en/global.json
This adds a select for past seasons on the ladder page, defaulting to the current season.
The action creators and reducers for all of this state got a bit messy, but not sure if there's a better way to deal with it.
Closes #1108
=> Add historical rankings to the ladder page.

server/lib/chat/chat-service.test.ts, server/lib/chat/chat-service.ts
Not *entirely* sure how this could happen, but it happened at least once that the user tried to leave the channel that didn't exist in the state anymore.
Fixes #1123
=> Add a more defensive code when user leaves the channel.

client/messaging/__snapshots__/common-message-layout.test.tsx.snap, client/messaging/common-message-layout.tsx
This should make it less likely for right-clicking the username to accidentally pop up chat message context menu if you were a couple of pixels off.
=> Add a little bit of vertical padding to usernames in chat messages.

client/games/game-players-display.tsx, client/users/match-history.tsx, client/users/mini-match-history.tsx
This has the benefit of being able to use gaps instead of margins, and also not having to insert fake elements to keep the teams ordered.
This commit also changes the order in which the teams/players are ordered so they always keep the consistent order. Basically the ordering follows two rules:
- Put the team/player of the user whose profile we're currently viewing on the left side
- Order the players within team alphabetically
Fixes #1166, #1161
=> Refactor the game players display to use flexbox instead of CSS columns.

client/debug/jotai-devtools.tsx
Chrome uses Ctrl + Shift + I to open the devtools (and focus on the elements tab), so we explicitly check that the Shift key is not pressed when opening the jotai devtools.
=> Change the jotai devtools hotkey so it doesn't clash with chrome devtools.

client/dom/auto-size-image.tsx, client/maps/map-image.tsx, client/maps/map-preview.tsx, client/maps/map-thumbnail.tsx, client/matchmaking/live-games-home-feed.tsx, client/material/devonly/slider-test.jsx, client/material/slider.tsx, server/public/locales/en/global.json
Not a perfect implementation by all means, but might be enough for now?
Things that could be improved:
- add pinch/touch gestures for mobile support
- make the pan speed smoother on all zoom levels
- add the "slide" effect when panning fast and releasing a mouse (similar to what happens on phones / google maps)
- make the image quality even better than 2048x2048 on the highest zoom level?
- pull this logic into a common hook / control component that can be used on any element? (might come in handy if/when we add tournament brackets)
Also fixes one issue with buttons where if you release a mouse on a disabled button, a `mouseup` event on the document would not run (this conflicted with the slider), and adds a prop to render the slider component without a balloon that shows the value.
=> Add a way to zoom in and pan around map image preview.

client/users/match-history.tsx
We already did have the code that tried to do this with flex, but since both of these items have `width: 100%` set (to make `singleLine` CSS work), the flex align had no effect.
I'm still of the opinion that this whole table could probably be rewritten with CSS Grid in a better way, but that will have to wait for some other time :d
=> Right-align the map name and game type in match history.

client/chat/channel-menu-items.tsx, client/dom/use-context-menu.tsx, client/messaging/chat-context.tsx, client/messaging/chat.tsx, client/messaging/common-message-layout.tsx, client/messaging/message-context-menu.tsx, client/users/user-context-menu.tsx, server/public/locales/en/global.json
Currently we add 2 actions:
- "Copy" -> copies selected text to the clipboard
- "Search with Google" -> opens a new tab in browser and initiates a google search
Maybe we could add an action to translate the selected text as well? But that seems like more work, so gonna leave it for later :d
=> Add some common actions when right-clicking selected text in chat.

client/chat/channel-menu-items.tsx, client/material/menu/item.tsx, client/material/menu/menu-item-symbol.ts, server/lib/chat/chat-service.ts
Previously these actions would only show up *after* we fetched the target user's chat profile, which could potentially make the whole context menu change the position due to new increased height.
Now these actions are always shown and enabled for server moderators and channel owners, and we only need to wait for the target's chat profile in case a channel moderator is opening the context menu.
This commit also does the following two things:
- adds disabled state to the menu items
- fixes a condition which checks if the user is a channel owner in the service method that returns the user's chat profile
=> Always show kick/ban actions in user's channel context menu.

client/i18n/action-creators.ts, client/material/radio.tsx, client/settings/settings.tsx, client/settings/user/language-settings.tsx, integration/tests/settings/language-change.spec.ts
By not trying to update the language on backend for non-existent user.
This commit also adds an integration tests to check changing the language settings for both the logged out and logged in users.
=> Fix the changing of language settings to work for logged out users.
